-- =====================================================
-- Day 6 - Sales Trend Analysis Using SQL
-- Data Analytics Internship
-- Author: Ravikumar Gujar
-- =====================================================
